import {_splitKeys, type ComponentType, type Props} from '@sanity/ui/core'
import {
  text,
  TEXT_STYLE_PROP_KEYS,
  textOverflow,
  type TextOverflowStyleProps,
  type TextStyleProps,
} from '@sanity/ui/css'

/**
 * The default HTML element type rendered by the {@link Text} component.
 *
 * @public
 */
export const DEFAULT_TEXT_ELEMENT = 'div'

/**
 * Style props for the {@link Text} component.
 *
 * @remarks
 * Combines {@link TextStyleProps} and {@link TextOverflowStyleProps} to provide
 * typographic styling and text overflow behavior.
 *
 * @public
 */
export type TextOwnProps = TextStyleProps & TextOverflowStyleProps

/**
 * Accepted values for the `as` prop of the {@link Text} component.
 *
 * @remarks
 * Determines the HTML element or custom component type rendered by `Text`.
 * The rendered element receives all applicable HTML attributes for the chosen
 * element type in addition to the Text's own style props.
 *
 * @public
 */
export type TextElementType =
  | 'div'
  | 'h1'
  | 'h2'
  | 'h3'
  | 'h4'
  | 'h5'
  | 'h6'
  | 'label'
  | 'li'
  | 'p'
  | 'span'
  | 'summary'
  | 'time'
  | ComponentType

/**
 * Props for the {@link Text} component.
 *
 * @remarks
 * Combines {@link TextOwnProps} with the intrinsic HTML attributes of the
 * element type specified by the `as` prop. When `as` is not provided,
 * the component renders a `<div>` element by default.
 *
 * @typeParam E - The HTML element or component type to render.
 *
 * @public
 */
export type TextProps<E extends TextElementType = TextElementType> = Props<TextOwnProps, E>

/**
 * A themed typographic element for rendering body text, captions, and other
 * general-purpose text content.
 *
 * @remarks
 * The `Text` component renders a single HTML element (default `<div>`) styled
 * with the theme's text typography scale. It maps style props to CSS class names
 * generated by the design system's CSS utility layer.
 *
 * @public
 */
export function Text<E extends TextElementType = typeof DEFAULT_TEXT_ELEMENT>(
  props: TextProps<E>,
): React.JSX.Element {
  const [
    styleProps,
    {
      as: Element = DEFAULT_TEXT_ELEMENT,
      children: childrenProp,
      textOverflow: textOverflowProp,
      // split DOM props
      ...domProps
    },
  ] = _splitKeys(props as TextProps<typeof DEFAULT_TEXT_ELEMENT>, TEXT_STYLE_PROP_KEYS)

  let children = childrenProp

  if (textOverflowProp) {
    children = <span className={textOverflow({textOverflow: textOverflowProp})}>{children}</span>
  }

  return (
    <Element data-ui="Text" {...domProps} className={text(styleProps)}>
      {children}
    </Element>
  )
}
