import type {Rules} from '../../types'

export const tokenRules: Rules = {
  token: {
    '@nest': {
      '&.atrule': {color: 'var(--color-token-atrule)'},
      '&.attr-name': {color: 'var(--color-token-attr-name)'},
      '&.attr-value': {color: 'var(--color-token-attr-value)'},
      '&.attribute': {color: 'var(--color-token-attribute)'},
      '&.boolean': {color: 'var(--color-token-boolean)'},
      '&.builtin': {color: 'var(--color-token-builtin)'},
      '&.cdata': {color: 'var(--color-token-cdata)'},
      '&.char': {color: 'var(--color-token-char)'},
      '&.class': {color: 'var(--color-token-class)'},
      '&.class-name': {color: 'var(--color-token-class-name)'},
      '&.comment': {color: 'var(--color-token-comment)'},
      '&.constant': {color: 'var(--color-token-constant)'},
      '&.deleted': {color: 'var(--color-token-deleted)'},
      '&.doctype': {color: 'var(--color-token-doctype)'},
      '&.entity': {color: 'var(--color-token-entity)'},
      '&.function': {color: 'var(--color-token-function)'},
      '&.hexcode': {color: 'var(--color-token-hexcode)'},
      '&.id': {color: 'var(--color-token-id)'},
      '&.important': {color: 'var(--color-token-important)'},
      '&.inserted': {color: 'var(--color-token-inserted)'},
      '&.keyword': {color: 'var(--color-token-keyword)'},
      '&.number': {color: 'var(--color-token-number)'},
      '&.operator': {color: 'var(--color-token-operator)'},
      '&.prolog': {color: 'var(--color-token-prolog)'},
      '&.property': {color: 'var(--color-token-property)'},
      '&.pseudo-class': {color: 'var(--color-token-pseudo-class)'},
      '&.pseudo-element': {color: 'var(--color-token-pseudo-element)'},
      '&.punctuation': {color: 'var(--color-token-punctuation)'},
      '&.attr-value &:not(.attr-equals).punctuation': {color: 'inherit'},
      '&.regex': {color: 'var(--color-token-regex)'},
      '&.selector': {color: 'var(--color-token-selector)'},
      '&.string': {color: 'var(--color-token-string)'},
      '&.symbol': {color: 'var(--color-token-symbol)'},
      '&.tag': {color: 'var(--color-token-tag)'},
      '&.unit': {color: 'var(--color-token-unit)'},
      '&.url': {color: 'var(--color-token-url)'},
      '&.variable': {color: 'var(--color-token-variable)'},
    },
  },
}
