import type {Rules} from '../../types'
// import {vars} from '../../vars'

export const tokenRules: Rules = {
  token: {
    '@nest': {
      // '&.atrule': {color: vars.color.syntax.atrule},
      // '&.attr-name': {color: vars.color.syntax.attrName},
      // '&.attr-value': {color: vars.color.syntax.attrValue},
      // '&.attribute': {color: vars.color.syntax.attribute},
      // '&.boolean': {color: vars.color.syntax.boolean},
      // '&.builtin': {color: vars.color.syntax.builtin},
      // '&.cdata': {color: vars.color.syntax.cdata},
      // '&.char': {color: vars.color.syntax.char},
      // '&.class': {color: vars.color.syntax.class},
      // '&.class-name': {color: vars.color.syntax.className},
      // '&.comment': {color: vars.color.syntax.comment},
      // '&.constant': {color: vars.color.syntax.constant},
      // '&.deleted': {color: vars.color.syntax.deleted},
      // '&.doctype': {color: vars.color.syntax.doctype},
      // '&.entity': {color: vars.color.syntax.entity},
      // '&.function': {color: vars.color.syntax.function},
      // '&.hexcode': {color: vars.color.syntax.hexcode},
      // '&.id': {color: vars.color.syntax.id},
      // '&.important': {color: vars.color.syntax.important},
      // '&.inserted': {color: vars.color.syntax.inserted},
      // '&.keyword': {color: vars.color.syntax.keyword},
      // '&.number': {color: vars.color.syntax.number},
      // '&.operator': {color: vars.color.syntax.operator},
      // '&.prolog': {color: vars.color.syntax.prolog},
      // '&.property': {color: vars.color.syntax.property},
      // '&.pseudo-class': {color: vars.color.syntax.pseudoClass},
      // '&.pseudo-element': {color: vars.color.syntax.pseudoElement},
      // '&.punctuation': {color: vars.color.syntax.punctuation},
      // '&.regex': {color: vars.color.syntax.regex},
      // '&.selector': {color: vars.color.syntax.selector},
      // '&.string': {color: vars.color.syntax.string},
      // '&.symbol': {color: vars.color.syntax.symbol},
      // '&.tag': {color: vars.color.syntax.tag},
      // '&.unit': {color: vars.color.syntax.unit},
      // '&.url': {color: vars.color.syntax.url},
      // '&.variable': {color: vars.color.syntax.variable},
    },
  },
}
