import {text, textOverflow, type TextOverflowStyleProps, type TextStyleProps} from '@sanity/ui/css'

import type {ComponentType, Props} from '../../types'

/**
 * The default HTML element type rendered by the {@link Text} component.
 *
 * @public
 */
export const DEFAULT_TEXT_ELEMENT = 'div'

/**
 * Own props for the {@link Text} component.
 *
 * @remarks
 * Extends {@link TextStyleProps} and {@link TextOverflowStyleProps} to combine
 * typographic control with text overflow handling.
 *
 * Inherited from {@link TextStyleProps}:
 * - `align` (`TextAlign`) – Controls horizontal text alignment. Accepted values: `"left"` | `"right"` | `"center"` | `"justify"` | `"initial"`.
 * - `className` (`string`) – A custom CSS class name to append to the element.
 * - `muted` (`boolean`) – Reduces visual prominence by applying a muted foreground color.
 * - `size` (`ResponsiveProp<FontTextSize>`) – Sets the font size using the theme's text size scale. Accepted values: `0 | 1 | 2 | 3 | 4`. Default: `2`.
 * - `weight` (`FontWeight`) – Sets the font weight. Accepted values: `"regular"` | `"medium"` | `"semibold"` | `"bold"`. Default: `"regular"`.
 * - `flex` (`ResponsiveProp<Flex>`) – Controls the flex grow/shrink behavior.
 * - `margin`, `marginX`, `marginY`, `marginTop`, `marginRight`, `marginBottom`, `marginLeft` – Margin props from the theme spacing scale.
 * - `maxWidth` (`ResponsiveProp<MaxWidth>`) – Constrains the maximum width. Default: `"fill"`.
 *
 * Inherited from {@link TextOverflowStyleProps}:
 * - `textOverflow` (`TextOverflow`) – Controls how overflowing text is treated. Accepted values: `"ellipsis"` | `"clip"`.
 *
 * @public
 */
export type TextOwnProps = TextStyleProps & TextOverflowStyleProps

/**
 * Accepted values for the `as` prop of the {@link Text} component.
 *
 * @remarks
 * Determines the HTML element or custom component type rendered by `Text`.
 * The rendered element receives all applicable HTML attributes for the chosen
 * element type in addition to the Text's own style props.
 *
 * Accepted values:
 * `"div"` | `"h1"` | `"h2"` | `"h3"` | `"h4"` | `"h5"` | `"h6"` | `"label"` |
 * `"li"` | `"p"` | `"span"` | `"summary"` | `"time"` | `ComponentType`
 *
 * @public
 */
export type TextElementType =
  | 'div'
  | 'h1'
  | 'h2'
  | 'h3'
  | 'h4'
  | 'h5'
  | 'h6'
  | 'label'
  | 'li'
  | 'p'
  | 'span'
  | 'summary'
  | 'time'
  | ComponentType

/**
 * Props for the {@link Text} component.
 *
 * @remarks
 * Combines {@link TextOwnProps} with the intrinsic HTML attributes of the
 * element type specified by the `as` prop. When `as` is not provided,
 * the component renders a `<div>` element by default.
 *
 * @typeParam E - The HTML element or component type to render. Defaults to {@link TextElementType}.
 *
 * @public
 */
export type TextProps<E extends TextElementType = TextElementType> = Props<TextOwnProps, E>

/**
 * A themed typographic element for rendering body text, captions, and other
 * general-purpose text content.
 *
 * @remarks
 * The `Text` component renders a single HTML element (default `<div>`) styled
 * with the theme's text typography scale. It maps style props to CSS class names
 * generated by the design system's CSS utility layer.
 *
 * The inner text content is wrapped in a `<span>` that can apply text overflow
 * truncation via the `textOverflow` prop.
 *
 * ### Props
 *
 * | Prop | Type | Default | Required | Description |
 * |------|------|---------|----------|-------------|
 * | `as` | `TextElementType` | `"div"` | No | The HTML element or component type to render. |
 * | `align` | `TextAlign` | `undefined` | No | Sets horizontal text alignment (`"left"` \| `"right"` \| `"center"` \| `"justify"` \| `"initial"`). |
 * | `muted` | `boolean` | `undefined` | No | Applies a muted foreground color from the theme. |
 * | `size` | `ResponsiveProp<FontTextSize>` | `2` | No | Sets the font size using the theme's text size scale (`0 \| 1 \| 2 \| 3 \| 4`). |
 * | `weight` | `FontWeight` | `"regular"` | No | Sets the font weight (`"regular"` \| `"medium"` \| `"semibold"` \| `"bold"`). |
 * | `textOverflow` | `TextOverflow` | `undefined` | No | Controls how overflowing text is treated (`"ellipsis"` \| `"clip"`). |
 * | `flex` | `ResponsiveProp<Flex>` | `undefined` | No | Controls flex grow/shrink behavior. |
 * | `margin` | `ResponsiveProp<Margin>` | `undefined` | No | Sets outer margin on all sides. |
 * | `maxWidth` | `ResponsiveProp<MaxWidth>` | `"fill"` | No | Constrains the maximum width of the text element. |
 *
 * @public
 */
export function Text<E extends TextElementType = typeof DEFAULT_TEXT_ELEMENT>(
  props: TextProps<E>,
): React.JSX.Element {
  const {
    align,
    as: Element = DEFAULT_TEXT_ELEMENT,
    children,
    className,
    flex,
    margin,
    marginX,
    marginY,
    marginTop,
    marginRight,
    marginBottom,
    marginLeft,
    maxWidth = 'fill',
    muted,
    size = 2,
    textOverflow: textOverflowProp,
    weight = 'regular',
    ...rest
  } = props as TextProps<typeof DEFAULT_TEXT_ELEMENT>

  return (
    <Element
      data-ui="Text"
      {...rest}
      className={text({
        className,
        align,
        flex,
        margin,
        marginX,
        marginY,
        marginTop,
        marginRight,
        marginBottom,
        marginLeft,
        maxWidth,
        muted,
        size,
        weight,
      })}
    >
      <span
        className={textOverflow({
          textOverflow: textOverflowProp,
        })}
      >
        {children}
      </span>
    </Element>
  )
}
