import type {AttributeMods} from '../../types/AnyExpression'

export const LAYOUT_MODS: AttributeMods = {
  border: {
    type: 'mapped-only',
    mapping: {
      none: false,
      muted: true,
      default: true,
    },
  },
  borderTop: {
    type: 'mapped-only',
    mapping: {
      none: false,
      muted: true,
      default: true,
    },
  },
  borderRight: {
    type: 'mapped-only',
    mapping: {
      none: false,
      muted: true,
      default: true,
    },
  },
  borderBottom: {
    type: 'mapped-only',
    mapping: {
      none: false,
      muted: true,
      default: true,
    },
  },
  borderLeft: {
    type: 'mapped-only',
    mapping: {
      none: false,
      muted: true,
      default: true,
    },
  },
  borderWidth: {type: 'remove'},
  flex: {
    type: 'composite-mapped',
    composition: [
      {
        name: 'flexBasis',
        mapping: {
          none: 'auto',
          auto: 'auto',
          initial: 'auto',
          1: '1',
          2: '2',
          3: '3',
          4: '4',
          5: '5',
          6: '6',
          7: '7',
          8: '8',
          9: '9',
          10: '10',
          11: '11',
          12: '12',
        },
      },
      {
        name: 'flexGrow',
        mapping: {
          none: '0',
          auto: '1',
          initial: '0',
          1: '1',
          2: '2',
          3: '3',
          4: '4',
          5: '5',
          6: '6',
          7: '7',
          8: '8',
          9: '9',
          10: '10',
          11: '11',
          12: '12',
        },
      },
      {
        name: 'flexShrink',
        mapping: {
          none: '0',
          auto: '1',
          initial: '1',
        },
      },
    ],
  },
  gapX: {
    type: 'rename-only',
    name: 'rowGap',
  },
  gapY: {
    type: 'rename-only',
    name: 'columnGap',
  },
  gridColumn: {
    type: 'mapped-only',
    mapping: {
      auto: 'auto',
      full: '1 / -1',
      1: 'span 1 / span 1',
      2: 'span 2 / span 2',
      3: 'span 3 / span 3',
      4: 'span 4 / span 4',
      5: 'span 5 / span 5',
      6: 'span 6 / span 6',
      7: 'span 7 / span 7',
      8: 'span 8 / span 8',
      9: 'span 9 / span 9',
      10: 'span 10 / span 10',
      11: 'span 11 / span 11',
      12: 'span 12 / span 12',
    },
  },
  gridColumnEnd: {
    type: 'mapped-only',
    mapping: {
      auto: 'auto',
      1: '1',
      2: '2',
      3: '3',
      4: '4',
      5: '5',
      6: '6',
      7: '7',
      8: '8',
      9: '9',
      10: '10',
      11: '11',
      12: '12',
    },
  },
  gridColumnStart: {
    type: 'mapped-only',
    mapping: {
      auto: 'auto',
      1: '1',
      2: '2',
      3: '3',
      4: '4',
      5: '5',
      6: '6',
      7: '7',
      8: '8',
      9: '9',
      10: '10',
      11: '11',
      12: '12',
    },
  },
  gridRow: {
    type: 'mapped-only',
    mapping: {
      auto: 'auto',
      full: '1 / -1',
      1: 'span 1 / span 1',
      2: 'span 2 / span 2',
      3: 'span 3 / span 3',
      4: 'span 4 / span 4',
      5: 'span 5 / span 5',
      6: 'span 6 / span 6',
      7: 'span 7 / span 7',
      8: 'span 8 / span 8',
      9: 'span 9 / span 9',
      10: 'span 10 / span 10',
      11: 'span 11 / span 11',
      12: 'span 12 / span 12',
    },
  },
  gridRowEnd: {
    type: 'mapped-only',
    mapping: {
      auto: 'auto',
      1: '1',
      2: '2',
      3: '3',
      4: '4',
      5: '5',
      6: '6',
      7: '7',
      8: '8',
      9: '9',
      10: '10',
      11: '11',
      12: '12',
    },
  },
  gridRowStart: {
    type: 'mapped-only',
    mapping: {
      auto: 'auto',
      1: '1',
      2: '2',
      3: '3',
      4: '4',
      5: '5',
      6: '6',
      7: '7',
      8: '8',
      9: '9',
      10: '10',
      11: '11',
      12: '12',
    },
  },
  height: {
    type: 'mapped-only',
    mapping: {
      fill: '100%',
      auto: 'auto',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
      stretch: 'stretch',
    },
  },
  insetTop: {
    type: 'rename-only',
    name: 'top',
  },
  insetRight: {
    type: 'rename-only',
    name: 'right',
  },
  insetBottom: {
    type: 'rename-only',
    name: 'bottom',
  },
  insetLeft: {
    type: 'rename-only',
    name: 'left',
  },
  maxWidth: {
    type: 'mapped-only',
    mapping: {
      auto: 'none',
      fill: '100%',
      0: '20rem',
      1: '40rem',
      2: '60rem',
      3: '80rem',
      4: '100rem',
      5: '120rem',
    },
  },
  minWidth: {
    type: 'mapped-only',
    mapping: {
      full: '100%',
      0: '0',
      auto: 'auto',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
    },
  },
  muted: {type: 'remove'},
  outline: {
    type: 'style-only',
    style: 'outline',
  },
  pointerEvents: {
    type: 'style-only',
    style: 'pointerEvents',
  },
  shadow: {type: 'remove'},
  sizing: {
    type: 'style-mapped',
    style: 'boxSizing',
    mapping: {
      content: 'content-box',
      border: 'border-box',
    },
  },
  textAlign: {
    type: 'style-only',
    style: 'textAlign',
  },
  width: {
    type: 'mapped-only',
    mapping: {
      auto: 'auto',
      fill: '100%',
      stretch: 'stretch',
      min: 'min-content',
      max: 'max-content',
      0: '20rem',
      1: '40rem',
      2: '60rem',
      3: '80rem',
      4: '100rem',
      5: '120rem',
    },
  },
}
