import {color, COLOR_TINTS, ColorHueKey, ColorTintKey, ColorTints} from '@sanity/color'

import {hexToHsl, Hsl, hslToHex, mixHue, relativeLuminance} from './hsl'
import {
  BuildThemeOptions,
  DEFAULT_ACCENT,
  DEFAULT_CONTRAST,
  DEFAULT_TEXT,
  MAXIMUM_CONTRAST,
  MINIMUM_CONTRAST,
  resolveThemeOptions,
} from './options'

/**
 * The lightness band the accent and text colors are clamped into — anchors
 * outside it would squeeze most of their scale's tints into an
 * indistinguishable sliver, messing with the rest of the scale.
 */
const MINIMUM_ANCHOR_LIGHTNESS = 0.25
const MAXIMUM_ANCHOR_LIGHTNESS = 0.75

/**
 * The contrast ratio the dark background must reach against the 400 tints of
 * the text and accent scales — the tints Sanity UI paints muted text and
 * solid buttons with on dark backgrounds. The stock palette sits at ~6.8.
 */
const MINIMUM_DARK_BACKGROUND_CONTRAST = 4.5

/** How much lightness each step of a background adjustment removes or adds */
const BACKGROUND_LIGHTNESS_STEP = 0.005

/**
 * The color palette generated by {@link buildPalette}: the `palette` config
 * of `buildTheme` from `@sanity/ui/theme`, with every color as a hex string.
 *
 * @public
 */
export type GeneratedColorPalette = {black: string; white: string} & Record<
  ColorHueKey,
  Record<ColorTintKey, string>
>

/**
 * Generates a Sanity UI color palette from the theme options: the accent
 * color replaces the `blue` scale, the text color the `gray` scale, and the
 * backgrounds replace `black` and `white`. All other hues keep their stock
 * `@sanity/color` values. Called with the stock colors, it returns the stock
 * palette byte-for-byte.
 *
 * ```ts
 * import {buildPalette} from '@sanity/themer'
 *
 * const palette = buildPalette({accent: '#556bfc'})
 * ```
 *
 * @public
 */
export function buildPalette(options: BuildThemeOptions): GeneratedColorPalette {
  const resolved = resolveThemeOptions(options)

  const accentAnchor = clampAnchorLightness(hexToHsl(resolved.accent))
  const textAnchor = clampAnchorLightness(hexToHsl(resolved.text))
  const grayAnchor = applyContrast(textAnchor, accentAnchor, resolved.contrast)

  const blueTints = remapTints(color.blue, hexToHsl(DEFAULT_ACCENT), accentAnchor)
  const grayTints = remapTints(color.gray, hexToHsl(DEFAULT_TEXT), grayAnchor)

  const anchorLuminances = [
    relativeLuminance(hslToHex(grayAnchor)),
    relativeLuminance(hslToHex(accentAnchor)),
  ]

  return {
    black: darkenBackground(resolved.background.dark, {
      anchorLuminances,
      tints: [grayTints['400'], blueTints['400']],
    }),
    white: lightenBackground(resolved.background.light, anchorLuminances),
    gray: grayTints,
    blue: blueTints,
    purple: tintHexes(color.purple),
    magenta: tintHexes(color.magenta),
    red: tintHexes(color.red),
    orange: tintHexes(color.orange),
    yellow: tintHexes(color.yellow),
    green: tintHexes(color.green),
    cyan: tintHexes(color.cyan),
  }
}

/**
 * Mixes the accent color into the text color according to the contrast: 85
 * applies the text color as-is, 100 removes its tint entirely, and lower
 * values rotate and saturate it towards the accent.
 */
function applyContrast(text: Hsl, accent: Hsl, contrast: number): Hsl {
  if (contrast === DEFAULT_CONTRAST) {
    return text
  }

  if (contrast > DEFAULT_CONTRAST) {
    const amount = (contrast - DEFAULT_CONTRAST) / (MAXIMUM_CONTRAST - DEFAULT_CONTRAST)

    return {h: text.h, s: text.s * (1 - amount), l: text.l}
  }

  const amount = (DEFAULT_CONTRAST - contrast) / (DEFAULT_CONTRAST - MINIMUM_CONTRAST)

  return {
    h: mixHue(text.h, accent.h, amount),
    s: text.s + (accent.s - text.s) * amount,
    l: text.l,
  }
}

/**
 * Rebuilds a stock tint scale around a new anchor color, where `from` is the
 * scale's stock 500 tint: hues rotate along, saturation scales
 * proportionally, and lightness is remapped piecewise so the anchor takes the
 * new lightness while the scale keeps spanning light to dark. When the anchor
 * matches the stock one, every tint comes back unchanged.
 */
function remapTints(tints: ColorTints, from: Hsl, to: Hsl): Record<ColorTintKey, string> {
  const rotation = to.h - from.h
  const result: Partial<Record<ColorTintKey, string>> = {}

  for (const tint of COLOR_TINTS) {
    const value = hexToHsl(tints[tint].hex)

    result[tint] = hslToHex({
      h: value.h + rotation,
      s: remapSaturation(value.s, from.s, to.s),
      l: remapLightness(value.l, from.l, to.l),
    })
  }

  // oxlint-disable-next-line no-unsafe-type-assertion -- the loop assigns every tint key
  return result as Record<ColorTintKey, string>
}

function remapSaturation(value: number, from: number, to: number): number {
  if (from === to) {
    return value
  }

  return Math.min(1, value * (to / from))
}

function remapLightness(value: number, from: number, to: number): number {
  if (from === to) {
    return value
  }

  if (value <= from) {
    return value * (to / from)
  }

  return to + ((value - from) * (1 - to)) / (1 - from)
}

function clampAnchorLightness(anchor: Hsl): Hsl {
  const l = Math.min(MAXIMUM_ANCHOR_LIGHTNESS, Math.max(MINIMUM_ANCHOR_LIGHTNESS, anchor.l))

  return l === anchor.l ? anchor : {...anchor, l}
}

/**
 * Enforces the dark background rules: it can never be lighter than the text
 * or accent colors, and it must reach enough contrast with the 400 tints of
 * their scales — it is made darker until it does (or bottoms out at black).
 */
function darkenBackground(
  hex: string,
  rules: {anchorLuminances: number[]; tints: string[]},
): string {
  const maximumLuminance = Math.min(...rules.anchorLuminances)
  const tintLuminances = rules.tints.map((tint) => relativeLuminance(tint))

  const isDarkEnough = (background: string): boolean => {
    const luminance = relativeLuminance(background)

    return (
      luminance < maximumLuminance &&
      tintLuminances.every(
        (tintLuminance) =>
          (tintLuminance + 0.05) / (luminance + 0.05) >= MINIMUM_DARK_BACKGROUND_CONTRAST,
      )
    )
  }

  const {h, s, l} = hexToHsl(hex)
  let lightness = l
  let current = hex

  while (!isDarkEnough(current) && lightness > 0) {
    lightness = Math.max(0, lightness - BACKGROUND_LIGHTNESS_STEP)
    current = hslToHex({h, s, l: lightness})
  }

  return current
}

/**
 * Enforces the light background rule: it can never be darker than the text
 * or accent colors — it is made lighter until it is (or tops out at white).
 */
function lightenBackground(hex: string, anchorLuminances: number[]): string {
  const minimumLuminance = Math.max(...anchorLuminances)

  const {h, s, l} = hexToHsl(hex)
  let lightness = l
  let current = hex

  while (relativeLuminance(current) <= minimumLuminance && lightness < 1) {
    lightness = Math.min(1, lightness + BACKGROUND_LIGHTNESS_STEP)
    current = hslToHex({h, s, l: lightness})
  }

  return current
}

function tintHexes(tints: ColorTints): Record<ColorTintKey, string> {
  const result: Partial<Record<ColorTintKey, string>> = {}

  for (const tint of COLOR_TINTS) {
    result[tint] = tints[tint].hex
  }

  // oxlint-disable-next-line no-unsafe-type-assertion -- the loop assigns every tint key
  return result as Record<ColorTintKey, string>
}
