name: CI & Release

on:
  push:
    branches:
      - main
      - beta
      - alpha
  pull_request:
    branches:
      - main
      - beta
      - alpha

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v1
        with:
          cache: true
      - run: pnpm lint --format github
      - run: pnpm build

  knip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v1
        with:
          cache: true
      - run: pnpm knip --reporter github-actions

  test:
    runs-on: ${{ matrix.platform }}
    name: Node.js ${{ matrix.node-version }} / ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        node-version: [lts, latest]
        include:
          - platform: macos-latest
            node-version: lts
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v1
        with:
          cache: true
          runtime: node@${{ matrix.node-version }}
      - run: pnpm test
