name: CI & Release

on:
  push:
    branches:
      - main
      - beta
      - alpha
  pull_request:
    branches:
      - main
      - beta
      - alpha

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v1
        with:
          cache: true
      - run: pnpm lint --deny-warnings --format github
      - run: tsc --noEmit
      - run: pnpm build

  test:
    runs-on: ${{ matrix.platform }}
    name: Node.js ${{ matrix.node-version }} / ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        node-version: [lts, latest]
        include:
          - platform: macos-latest
            node-version: lts
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v1
        with:
          cache: true
          runtime: node@${{ matrix.node-version }}
      - run: pnpm test

  release:
    permissions:
      id-token: write # to enable use of OIDC for npm provenance
    name: "Semantic release"
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ vars.ECOSPARK_CLIENT_ID }}
          private-key: ${{ secrets.ECOSPARK_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v7
        with:
          # Need to fetch entire commit history to
          # analyze every commit since last release
          fetch-depth: 0
          # Uses generated token to allow pushing commits back
          token: ${{ steps.app-token.outputs.token }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
      - uses: pnpm/setup@v1
      - name: Update npm to use trusted publishing (OIDC)
        run: npm install -g npm@latest
      # Branches that will release new versions are defined in .releaserc.json
      - run: pnpm exec semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
