import {readFileSync, writeFileSync} from 'node:fs'
import {dirname, join} from 'node:path'
import {fileURLToPath} from 'node:url'

const current = dirname(fileURLToPath(import.meta.url))
const pkg = JSON.parse(readFileSync(join(current, '..', 'package.json'), 'utf8'))

const content = `// This file is generated by scripts/write-version.js. Do not edit.
export const VERSION = '${pkg.version.replace(/\./g, '').replace(/-/g, '')}'
`

writeFileSync(join(current, '..', 'src', 'version.ts'), content)
