import crypto from 'node:crypto'
import {readFileSync, writeFileSync} from 'node:fs'
import {dirname, join} from 'node:path'
import {fileURLToPath} from 'node:url'

const current = dirname(fileURLToPath(import.meta.url))
const pkg = JSON.parse(readFileSync(join(current, '..', 'package.json'), 'utf8'))
const version = pkg.version.replace(/\./g, '').replace(/-/g, '')

const encoder = new TextEncoder()
const data = encoder.encode(version)
const hashBuffer = await crypto.subtle.digest('SHA-256', data)
const hash = Buffer.from(hashBuffer).toString('hex').slice(0, 6)

const content = `// This file is generated by scripts/write-version.js. Do not edit.
export const VERSION = '${version}'
export const HASH = '${hash}'
`

writeFileSync(join(current, '..', 'src', 'version.ts'), content)
