export const primaryNavId = 'v3'
export const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID || 'mos42crl'
export const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET || 'production'
export const apiVersion = process.env.NEXT_PUBLIC_SANITY_API_VERSION || '2026-07-01'
export const basePath = (process.env.__NEXT_ROUTER_BASEPATH as string) || ''
