import {box, type BoxStyleProps} from '@sanity/ui/css'

import type {ComponentType, Props} from '../../types'

/**
 * The default HTML element type rendered by the {@link Box} component.
 *
 * @public
 */
export const DEFAULT_BOX_ELEMENT = 'div'

/**
 * Own props for the {@link Box} component.
 *
 * @remarks
 * Inherits all properties from {@link BoxStyleProps}, which provides a comprehensive set of
 * CSS utility style props for layout, spacing, sizing, positioning, and visual treatment.
 *
 * See {@link BoxStyleProps} for the full list of available style properties including:
 * - **Layout:** `display`, `flex`, `flexDirection`, `flexWrap`, `alignItems`, `justifyContent`
 * - **Spacing:** `margin`, `marginX`, `marginY`, `padding`, `paddingX`, `paddingY` (and per-side variants)
 * - **Sizing:** `width`, `height`, `minWidth`, `minHeight`, `maxWidth`
 * - **Grid:** `gap`, `gapX`, `gapY`, `gridTemplateColumns`, `gridTemplateRows`, and other grid props
 * - **Position:** `position`, `inset`, `insetTop`, `insetRight`, `insetBottom`, `insetLeft`
 * - **Visual:** `border`, `radius`, `shadow`, `overflow`, `muted`, `outline`
 * - **Text:** `textAlign`
 * - **Other:** `pointerEvents`, `sizing` (box-sizing)
 *
 * All style props support responsive values via the `ResponsiveProp` type, which accepts
 * either a single value or a breakpoint-keyed object (e.g. `{0: 2, 2: 4}`).
 *
 * @public
 */
export type BoxOwnProps = BoxStyleProps

/**
 * Accepted values for the `as` prop of the {@link Box} component.
 *
 * @remarks
 * Determines the HTML element or custom component type rendered by `Box`.
 * The rendered element receives all applicable HTML attributes for the chosen element type
 * in addition to the Box's own style props.
 *
 * Accepted values:
 * `"a"` | `"article"` | `"aside"` | `"blockquote"` | `"body"` | `"button"` | `"details"` |
 * `"div"` | `"header"` | `"fieldset"` | `"figure"` | `"figcaption"` | `"footer"` | `"form"` |
 * `"html"` | `"iframe"` | `"kbd"` | `"label"` | `"legend"` | `"li"` | `"main"` | `"nav"` |
 * `"ol"` | `"pre"` | `"section"` | `"span"` | `"summary"` | `"table"` | `"tbody"` | `"td"` |
 * `"tfoot"` | `"th"` | `"thead"` | `"tr"` | `"ul"` | `ComponentType`
 *
 * @public
 */
export type BoxElementType =
  | 'a'
  | 'article'
  | 'aside'
  | 'blockquote'
  | 'body'
  | 'button'
  | 'details'
  | 'div'
  | 'header'
  | 'fieldset'
  | 'figure'
  | 'figcaption'
  | 'footer'
  | 'form'
  | 'html'
  | 'iframe'
  | 'kbd'
  | 'label'
  | 'legend'
  | 'li'
  | 'main'
  | 'nav'
  | 'ol'
  | 'pre'
  | 'section'
  | 'span'
  | 'summary'
  | 'table'
  | 'tbody'
  | 'td'
  | 'tfoot'
  | 'th'
  | 'thead'
  | 'tr'
  | 'ul'
  | ComponentType

/**
 * Props for the {@link Box} component.
 *
 * @remarks
 * Combines {@link BoxOwnProps} with the intrinsic HTML attributes of the
 * element type specified by the `as` prop. When `as` is not provided,
 * the component renders a `<div>` element by default.
 *
 * @typeParam E - The HTML element or component type to render. Defaults to {@link BoxElementType}.
 *
 * @public
 */
export type BoxProps<E extends BoxElementType = BoxElementType> = Props<BoxOwnProps, E>

/**
 * The `Box` component is a foundational layout primitive that provides utility properties
 * for display, flex, grid, margins, padding, sizing, positioning, and visual treatment.
 *
 * @remarks
 * `Box` renders a single HTML element (default `<div>`) and maps its style props to
 * CSS class names generated by the design system's CSS utility layer.
 *
 * It serves as the building block for higher-level layout primitives such as
 * {@link Flex}, {@link Grid}, {@link Stack}, {@link Inline}, and {@link Card}.
 *
 * ### Props
 *
 * | Prop | Type | Default | Description |
 * |------|------|---------|-------------|
 * | `as` | {@link BoxElementType} | `"div"` | The HTML element or component type to render. |
 * | `display` | `ResponsiveProp<Display>` | `"block"` | Sets the CSS display mode. |
 * | `flex` | `ResponsiveProp<Flex>` | — | Controls the flex grow/shrink behavior. |
 * | `flexDirection` | `ResponsiveProp<FlexDirection>` | — | Sets the flex direction. |
 * | `flexWrap` | `ResponsiveProp<FlexWrap>` | — | Controls whether flex items wrap. |
 * | `alignItems` | `ResponsiveProp<AlignItems>` | — | Aligns items along the cross axis. |
 * | `justifyContent` | `ResponsiveProp<JustifyContent>` | — | Distributes items along the main axis. |
 * | `gap` | `ResponsiveProp<Space>` | — | Sets the gap between flex/grid children. |
 * | `gapX` | `ResponsiveProp<Space>` | — | Sets the horizontal gap. |
 * | `gapY` | `ResponsiveProp<Space>` | — | Sets the vertical gap. |
 * | `margin` | `ResponsiveProp<Margin>` | `0` | Sets the outer margin on all sides. |
 * | `marginX` | `ResponsiveProp<Margin>` | — | Sets the horizontal margin. |
 * | `marginY` | `ResponsiveProp<Margin>` | — | Sets the vertical margin. |
 * | `marginTop` | `ResponsiveProp<Margin>` | — | Sets the top margin. |
 * | `marginRight` | `ResponsiveProp<Margin>` | — | Sets the right margin. |
 * | `marginBottom` | `ResponsiveProp<Margin>` | — | Sets the bottom margin. |
 * | `marginLeft` | `ResponsiveProp<Margin>` | — | Sets the left margin. |
 * | `padding` | `ResponsiveProp<Padding>` | `0` | Sets the inner padding on all sides. |
 * | `paddingX` | `ResponsiveProp<Padding>` | — | Sets the horizontal padding. |
 * | `paddingY` | `ResponsiveProp<Padding>` | — | Sets the vertical padding. |
 * | `paddingTop` | `ResponsiveProp<Padding>` | — | Sets the top padding. |
 * | `paddingRight` | `ResponsiveProp<Padding>` | — | Sets the right padding. |
 * | `paddingBottom` | `ResponsiveProp<Padding>` | — | Sets the bottom padding. |
 * | `paddingLeft` | `ResponsiveProp<Padding>` | — | Sets the left padding. |
 * | `width` | `ResponsiveProp<Width>` | — | Sets the width. |
 * | `height` | `ResponsiveProp<Height>` | — | Sets the height. |
 * | `minWidth` | `ResponsiveProp<MinWidth>` | `0` | Sets the minimum width. |
 * | `minHeight` | `ResponsiveProp<MinHeight>` | `0` | Sets the minimum height. |
 * | `maxWidth` | `ResponsiveProp<MaxWidth>` | — | Sets the maximum width. |
 * | `position` | `ResponsiveProp<Position>` | — | Sets the CSS positioning scheme. |
 * | `inset` | `ResponsiveProp<Inset>` | — | Sets the inset on all sides. |
 * | `insetTop` | `ResponsiveProp<Inset>` | — | Sets the top inset. |
 * | `insetRight` | `ResponsiveProp<Inset>` | — | Sets the right inset. |
 * | `insetBottom` | `ResponsiveProp<Inset>` | — | Sets the bottom inset. |
 * | `insetLeft` | `ResponsiveProp<Inset>` | — | Sets the left inset. |
 * | `overflow` | `ResponsiveProp<Overflow>` | — | Controls overflow behavior on both axes. |
 * | `overflowX` | `ResponsiveProp<Overflow>` | — | Controls horizontal overflow behavior. |
 * | `overflowY` | `ResponsiveProp<Overflow>` | — | Controls vertical overflow behavior. |
 * | `border` | `ResponsiveProp<BorderStyle \| boolean>` | `false` | Sets the border on all sides. |
 * | `borderTop` | `ResponsiveProp<BorderStyle \| boolean>` | — | Sets the top border. |
 * | `borderRight` | `ResponsiveProp<BorderStyle \| boolean>` | — | Sets the right border. |
 * | `borderBottom` | `ResponsiveProp<BorderStyle \| boolean>` | — | Sets the bottom border. |
 * | `borderLeft` | `ResponsiveProp<BorderStyle \| boolean>` | — | Sets the left border. |
 * | `radius` | `ResponsiveProp<Radius \| 'full'>` | — | Sets the border radius. |
 * | `shadow` | `ResponsiveProp<Shadow>` | — | Sets the box shadow elevation. |
 * | `muted` | `boolean` | — | Applies a muted foreground color. |
 * | `outline` | `'none'` | — | Removes the focus outline. |
 * | `sizing` | `BoxSizing` | `"border"` | Controls box-sizing behavior. |
 * | `textAlign` | `TextAlign` | — | Sets horizontal text alignment. |
 * | `pointerEvents` | `PointerEvents` | — | Controls pointer event handling. |
 * | `gridTemplateColumns` | `ResponsiveProp<GridTemplateColumns>` | — | Defines grid column template. |
 * | `gridTemplateRows` | `ResponsiveProp<GridTemplateRows>` | — | Defines grid row template. |
 * | `gridAutoColumns` | `ResponsiveProp<GridAutoColumns>` | — | Sets implicit grid column sizing. |
 * | `gridAutoRows` | `ResponsiveProp<GridAutoRows>` | — | Sets implicit grid row sizing. |
 * | `gridAutoFlow` | `ResponsiveProp<GridAutoFlow>` | — | Controls auto-placement flow in a grid. |
 * | `gridColumn` | `ResponsiveProp<GridColumn>` | — | Controls grid item column span/placement. |
 * | `gridColumnStart` | `ResponsiveProp<GridColumnStart>` | — | Sets the starting column grid line. |
 * | `gridColumnEnd` | `ResponsiveProp<GridColumnEnd>` | — | Sets the ending column grid line. |
 * | `gridRow` | `ResponsiveProp<GridRow>` | — | Controls grid item row span/placement. |
 * | `gridRowStart` | `ResponsiveProp<GridRowStart>` | — | Sets the starting row grid line. |
 * | `gridRowEnd` | `ResponsiveProp<GridRowEnd>` | — | Sets the ending row grid line. |
 *
 * @public
 */
export function Box<E extends BoxElementType = typeof DEFAULT_BOX_ELEMENT>(
  props: BoxProps<E>,
): React.JSX.Element {
  const {
    alignItems,
    as: Element = DEFAULT_BOX_ELEMENT,
    // autoCols,
    // autoFlow,
    // autoRows,
    border = false,
    borderTop,
    borderRight,
    borderBottom,
    borderLeft,
    className,
    children,
    // column,
    // columnStart,
    // columnEnd,
    // columns,
    display = 'block',
    flex,
    flexDirection,
    flexWrap,
    gap,
    gapX,
    gapY,
    gridAutoColumns,
    gridAutoFlow,
    gridAutoRows,
    gridColumn,
    gridColumnEnd,
    gridColumnStart,
    gridRow,
    gridRowEnd,
    gridRowStart,
    gridTemplateColumns,
    gridTemplateRows,
    height,
    inset,
    insetBottom,
    insetLeft,
    insetRight,
    insetTop,
    justifyContent,
    margin = 0,
    marginX,
    marginY,
    marginTop,
    marginRight,
    marginBottom,
    marginLeft,
    maxWidth,
    minHeight = 0,
    minWidth = 0,
    muted,
    outline,
    overflow,
    overflowX,
    overflowY,
    padding = 0,
    paddingX,
    paddingY,
    paddingTop,
    paddingRight,
    paddingBottom,
    paddingLeft,
    pointerEvents,
    position,
    radius,
    // row,
    // rows,
    // rowStart,
    // rowEnd,
    shadow,
    sizing = 'border',
    textAlign,
    width,
    ...rest
  } = props as BoxProps<typeof DEFAULT_BOX_ELEMENT>

  return (
    <Element
      data-ui="Box"
      {...rest}
      className={box({
        className,
        alignItems,
        // autoCols,
        // autoFlow,
        // autoRows,
        border,
        borderTop,
        borderRight,
        borderBottom,
        borderLeft,
        // column,
        // columnStart,
        // columnEnd,
        // columns,
        display,
        flex,
        flexDirection,
        flexWrap,
        gap,
        gapX,
        gapY,
        gridAutoColumns,
        gridAutoFlow,
        gridAutoRows,
        gridColumn,
        gridColumnEnd,
        gridColumnStart,
        gridRow,
        gridRowEnd,
        gridRowStart,
        gridTemplateColumns,
        gridTemplateRows,
        height,
        inset,
        insetBottom,
        insetLeft,
        insetRight,
        insetTop,
        justifyContent,
        margin,
        marginX,
        marginY,
        marginTop,
        marginRight,
        marginBottom,
        marginLeft,
        maxWidth,
        minHeight,
        minWidth,
        muted,
        outline,
        overflow,
        overflowX,
        overflowY,
        padding,
        paddingX,
        paddingY,
        paddingTop,
        paddingRight,
        paddingBottom,
        paddingLeft,
        pointerEvents,
        position,
        radius,
        // row,
        // rows,
        // rowStart,
        // rowEnd,
        shadow,
        sizing,
        textAlign,
        width,
      })}
    >
      {children}
    </Element>
  )
}
