import {responsiveRules} from '../../responsiveRules'
import {type Rules} from '../../types'

export const gridItemRules: Rules = {
  // column
  ...responsiveRules('col-auto', {gridColumn: `span 1 / span 1`}),
  ...responsiveRules('col-full', {gridColumn: `1 / -1`}),
  ...responsiveRules('col-1', {gridColumn: `span 1 / span 1`}),
  ...responsiveRules('col-2', {gridColumn: `span 2 / span 2`}),
  ...responsiveRules('col-3', {gridColumn: `span 3 / span 3`}),
  ...responsiveRules('col-4', {gridColumn: `span 4 / span 4`}),
  ...responsiveRules('col-5', {gridColumn: `span 5 / span 5`}),
  ...responsiveRules('col-6', {gridColumn: `span 6 / span 6`}),
  ...responsiveRules('col-7', {gridColumn: `span 7 / span 7`}),
  ...responsiveRules('col-8', {gridColumn: `span 8 / span 8`}),
  ...responsiveRules('col-9', {gridColumn: `span 9 / span 9`}),
  ...responsiveRules('col-10', {gridColumn: `span 10 / span 10`}),
  ...responsiveRules('col-11', {gridColumn: `span 11 / span 11`}),
  ...responsiveRules('col-12', {gridColumn: `span 12 / span 12`}),

  // columnStart
  ...responsiveRules('col-start-auto', {gridColumnStart: 'auto'}),
  ...responsiveRules('col-start-1', {gridColumnStart: '1'}),
  ...responsiveRules('col-start-2', {gridColumnStart: '2'}),
  ...responsiveRules('col-start-3', {gridColumnStart: '3'}),
  ...responsiveRules('col-start-4', {gridColumnStart: '4'}),
  ...responsiveRules('col-start-5', {gridColumnStart: '5'}),
  ...responsiveRules('col-start-6', {gridColumnStart: '6'}),
  ...responsiveRules('col-start-7', {gridColumnStart: '7'}),
  ...responsiveRules('col-start-8', {gridColumnStart: '8'}),
  ...responsiveRules('col-start-9', {gridColumnStart: '9'}),
  ...responsiveRules('col-start-10', {gridColumnStart: '10'}),
  ...responsiveRules('col-start-11', {gridColumnStart: '11'}),
  ...responsiveRules('col-start-12', {gridColumnStart: '12'}),

  // columnEnd
  ...responsiveRules('col-end-auto', {gridColumnEnd: 'auto'}),
  ...responsiveRules('col-end-1', {gridColumnEnd: '1'}),
  ...responsiveRules('col-end-2', {gridColumnEnd: '2'}),
  ...responsiveRules('col-end-3', {gridColumnEnd: '3'}),
  ...responsiveRules('col-end-4', {gridColumnEnd: '4'}),
  ...responsiveRules('col-end-5', {gridColumnEnd: '5'}),
  ...responsiveRules('col-end-6', {gridColumnEnd: '6'}),
  ...responsiveRules('col-end-7', {gridColumnEnd: '7'}),
  ...responsiveRules('col-end-8', {gridColumnEnd: '8'}),
  ...responsiveRules('col-end-9', {gridColumnEnd: '9'}),
  ...responsiveRules('col-end-10', {gridColumnEnd: '10'}),
  ...responsiveRules('col-end-11', {gridColumnEnd: '11'}),
  ...responsiveRules('col-end-12', {gridColumnEnd: '12'}),

  // row
  ...responsiveRules('row-auto', {gridRow: `span 1 / span 1`}),
  ...responsiveRules('row-full', {gridRow: `1 / -1`}),
  ...responsiveRules('row-1', {gridRow: `span 1 / span 1`}),
  ...responsiveRules('row-2', {gridRow: `span 2 / span 2`}),
  ...responsiveRules('row-3', {gridRow: `span 3 / span 3`}),
  ...responsiveRules('row-4', {gridRow: `span 4 / span 4`}),
  ...responsiveRules('row-5', {gridRow: `span 5 / span 5`}),
  ...responsiveRules('row-6', {gridRow: `span 6 / span 6`}),
  ...responsiveRules('row-7', {gridRow: `span 7 / span 7`}),
  ...responsiveRules('row-8', {gridRow: `span 8 / span 8`}),
  ...responsiveRules('row-9', {gridRow: `span 9 / span 9`}),
  ...responsiveRules('row-10', {gridRow: `span 10 / span 10`}),
  ...responsiveRules('row-11', {gridRow: `span 11 / span 11`}),
  ...responsiveRules('row-12', {gridRow: `span 12 / span 12`}),

  // rowStart
  ...responsiveRules('row-start-auto', {gridRowStart: 'auto'}),
  ...responsiveRules('row-start-1', {gridRowStart: '1'}),
  ...responsiveRules('row-start-2', {gridRowStart: '2'}),
  ...responsiveRules('row-start-3', {gridRowStart: '3'}),
  ...responsiveRules('row-start-4', {gridRowStart: '4'}),
  ...responsiveRules('row-start-5', {gridRowStart: '5'}),
  ...responsiveRules('row-start-6', {gridRowStart: '6'}),
  ...responsiveRules('row-start-7', {gridRowStart: '7'}),
  ...responsiveRules('row-start-8', {gridRowStart: '8'}),
  ...responsiveRules('row-start-9', {gridRowStart: '9'}),
  ...responsiveRules('row-start-10', {gridRowStart: '10'}),
  ...responsiveRules('row-start-11', {gridRowStart: '11'}),
  ...responsiveRules('row-start-12', {gridRowStart: '12'}),

  // rowEnd
  ...responsiveRules('row-end-auto', {gridRowEnd: 'auto'}),
  ...responsiveRules('row-end-1', {gridRowEnd: '1'}),
  ...responsiveRules('row-end-2', {gridRowEnd: '2'}),
  ...responsiveRules('row-end-3', {gridRowEnd: '3'}),
  ...responsiveRules('row-end-4', {gridRowEnd: '4'}),
  ...responsiveRules('row-end-5', {gridRowEnd: '5'}),
  ...responsiveRules('row-end-6', {gridRowEnd: '6'}),
  ...responsiveRules('row-end-7', {gridRowEnd: '7'}),
  ...responsiveRules('row-end-8', {gridRowEnd: '8'}),
  ...responsiveRules('row-end-9', {gridRowEnd: '9'}),
  ...responsiveRules('row-end-10', {gridRowEnd: '10'}),
  ...responsiveRules('row-end-11', {gridRowEnd: '11'}),
  ...responsiveRules('row-end-12', {gridRowEnd: '12'}),
}
