import {ThemeProvider} from '@sanity/ui'
import {useEffect, useMemo, useState} from 'react'
import {type LayoutProps} from 'sanity'

import {buildTheme} from '../theme/buildTheme'
import {BuildThemeOptions} from '../theme/options'
import {ThemerContext, ThemerContextValue} from './context'
import {readStoredOptions, writeStoredOptions} from './storage'

/**
 * Wraps the whole Studio so that draft themes generated by the themer sidebar
 * apply everywhere while the user browses around, and hosts the state that the
 * navbar toggle and the sidebar share.
 *
 * The draft theme provider inherits the color scheme from the Studio, so the
 * preview follows the appearance setting (light/dark/system) like any other
 * theme.
 *
 * @internal
 */
export function ThemerLayout(props: LayoutProps & {baseOptions: BuildThemeOptions}) {
  const {baseOptions, ...layoutProps} = props
  const [open, setOpen] = useState(false)
  const [options, setOptions] = useState<BuildThemeOptions | null>(readStoredOptions)

  useEffect(() => writeStoredOptions(options), [options])

  // The theme identity must be stable between renders: it feeds the
  // styled-components theme context for the whole Studio, and rebuilding it
  // would re-render everything (the React Compiler caches it on `options`)
  const theme = options === null ? null : buildTheme(options)

  // The explicit useMemo is kept for oxlint's jsx-no-constructed-context-values,
  // which cannot know that the React Compiler already caches this object
  // react-doctor-disable-next-line react-doctor/react-compiler-no-manual-memoization
  const context = useMemo<ThemerContextValue>(
    () => ({baseOptions, options, setOptions, open, setOpen}),
    [baseOptions, options, open],
  )

  return (
    <ThemerContext.Provider value={context}>
      {theme === null ? (
        layoutProps.renderDefault(layoutProps)
      ) : (
        <ThemeProvider theme={theme}>{layoutProps.renderDefault(layoutProps)}</ThemeProvider>
      )}
    </ThemerContext.Provider>
  )
}
