import {ThemeProvider} from '@sanity/ui'
import {useEffect, useMemo, useState} from 'react'
import {type LayoutProps} from 'sanity'

import {createTheme} from '../createTheme'
import {CreateThemeOptions} from '../types'
import {ThemerContext, ThemerContextValue} from './context'
import {readStoredColors, writeStoredColors} from './storage'

/**
 * Wraps the whole Studio so that draft themes generated by the themer sidebar
 * apply everywhere while the user browses around, and hosts the state that the
 * navbar toggle and the sidebar share.
 *
 * The draft theme provider inherits the color scheme from the Studio, so the
 * preview follows the appearance setting (light/dark/system) like any other
 * theme.
 *
 * @internal
 */
export function ThemerLayout(props: LayoutProps & {baseColors: CreateThemeOptions}) {
  const {baseColors, ...layoutProps} = props
  const [open, setOpen] = useState(false)
  const [colors, setColors] = useState<CreateThemeOptions | null>(readStoredColors)

  useEffect(() => writeStoredColors(colors), [colors])

  // The theme identity must be stable between renders: it feeds the
  // styled-components theme context for the whole Studio, and rebuilding it
  // would re-render everything
  const theme = useMemo(
    () => (colors === null ? null : createTheme({...baseColors, ...colors})),
    [baseColors, colors],
  )

  const context = useMemo<ThemerContextValue>(
    () => ({baseColors, colors, setColors, open, setOpen}),
    [baseColors, colors, open],
  )

  return (
    <ThemerContext.Provider value={context}>
      {theme === null ? (
        layoutProps.renderDefault(layoutProps)
      ) : (
        <ThemeProvider theme={theme}>{layoutProps.renderDefault(layoutProps)}</ThemeProvider>
      )}
    </ThemerContext.Provider>
  )
}
