import {ThemeProvider} from '@sanity/ui'
import {useEffect, useMemo, useState} from 'react'
import {type LayoutProps} from 'sanity'

import {createTheme} from '../legacy/createTheme'
import {Hues} from '../legacy/types'
import {ThemerContext, ThemerContextValue} from './context'
import {readStoredHues, writeStoredHues} from './storage'

/**
 * Wraps the whole Studio so that draft themes generated by the themer sidebar
 * apply everywhere while the user browses around, and hosts the state that the
 * navbar toggle and the sidebar share.
 *
 * The draft theme provider inherits the color scheme from the Studio, so the
 * preview follows the appearance setting (light/dark/system) like any other
 * theme.
 *
 * @internal
 */
export function ThemerLayout(props: LayoutProps & {baseHues: Hues}) {
  const {baseHues, ...layoutProps} = props
  const [open, setOpen] = useState(false)
  const [hues, setHues] = useState<Hues | null>(readStoredHues)

  useEffect(() => writeStoredHues(hues), [hues])

  // The theme identity must be stable between renders: it feeds the
  // styled-components theme context for the whole Studio, and rebuilding it
  // would re-render everything
  const theme = useMemo(() => (hues === null ? null : createTheme(hues)), [hues])

  const context = useMemo<ThemerContextValue>(
    () => ({baseHues, hues, setHues, open, setOpen}),
    [baseHues, hues, open],
  )

  return (
    <ThemerContext.Provider value={context}>
      {theme === null ? (
        layoutProps.renderDefault(layoutProps)
      ) : (
        <ThemeProvider theme={theme}>{layoutProps.renderDefault(layoutProps)}</ThemeProvider>
      )}
    </ThemerContext.Provider>
  )
}
