import {Card, Flex, Layer, ThemeProvider} from '@sanity/ui'
import {useEffect, useMemo, useState} from 'react'
import {type LayoutProps} from 'sanity'

import {createTheme} from '../generator/createTheme'
import {Hues, LegacyTheme} from '../generator/types'
import {ThemerContext, ThemerContextValue, ThemerView} from './context'
import {readStoredHues, writeStoredHues} from './storage'
import {ThemerSidebar} from './ThemerSidebar'

/**
 * Wide enough for the three color inputs of a hue to sit next to each other
 * with their hex values, like the hosted Themer's sidebar.
 */
const SIDEBAR_WIDTH = 300

const sidebarStyle: React.CSSProperties = {
  width: SIDEBAR_WIDTH,
  flex: 'none',
  boxSizing: 'border-box',
  overflow: 'hidden',
}

/**
 * Wraps the whole Studio so that draft themes generated by the themer sidebar
 * apply everywhere while the user browses around, hosts the state that the
 * navbar toggle and the sidebar share, and renders the sidebar next to the
 * Studio. It sits at the `layout` level rather than in `activeToolLayout`
 * because the split preview renders the Studio twice — the sidebar must not
 * come along.
 *
 * The single preview inherits the color scheme from the Studio, so it follows
 * the appearance setting (light/dark/system) like any other theme.
 *
 * @internal
 */
export function ThemerLayout(props: LayoutProps) {
  const [open, setOpen] = useState(false)
  const [view, setView] = useState<ThemerView>('single')
  const [hues, setHues] = useState<Hues | null>(readStoredHues)

  useEffect(() => writeStoredHues(hues), [hues])

  // The theme identity must be stable between renders: it feeds the
  // styled-components theme context for the whole Studio, and rebuilding it
  // would re-render everything
  const theme = useMemo(() => (hues === null ? null : createTheme(hues)), [hues])

  const context = useMemo<ThemerContextValue>(
    () => ({hues, setHues, view, setView, open, setOpen}),
    [hues, view, open],
  )

  return (
    <ThemerContext.Provider value={context}>
      <Flex height="fill" sizing="border">
        {view === 'split' ? (
          <SplitPreview theme={theme}>{props.renderDefault(props)}</SplitPreview>
        ) : (
          <Preview theme={theme}>{props.renderDefault(props)}</Preview>
        )}

        {open && (
          <ThemeProvider theme={theme ?? undefined}>
            <Layer height="fill" style={sidebarStyle} zOffset={100}>
              <ThemerSidebar />
            </Layer>
          </ThemeProvider>
        )}
      </Flex>
    </ThemerContext.Provider>
  )
}

interface PreviewProps {
  children: React.ReactNode
  /** The draft theme, or `null` to preview the theme the Studio is configured with */
  theme: LegacyTheme | null
}

/**
 * The Studio in the appearance it is set to. An untouched draft still goes
 * through the provider (inheriting the Studio's theme and scheme), so the first
 * edit swaps themes instead of remounting the Studio under a new provider.
 */
function Preview(props: PreviewProps) {
  const {children, theme} = props

  return (
    <ThemeProvider theme={theme ?? undefined}>
      <Card flex={1} height="fill" overflow="hidden">
        {children}
      </Card>
    </ThemeProvider>
  )
}

/**
 * The Studio twice, side by side: light on the left, dark on the right. Both
 * copies share the router, the document store and every other provider above
 * the layout — only the theme scheme differs — so they stay in sync while
 * navigating. The `color-scheme` on each half keeps native form controls and
 * scrollbars in step with the forced scheme.
 */
function SplitPreview(props: PreviewProps) {
  const {children, theme} = props

  return (
    <>
      <ThemeProvider scheme="light" theme={theme ?? undefined}>
        <Card flex={1} height="fill" overflow="hidden" style={{colorScheme: 'light'}}>
          {children}
        </Card>
      </ThemeProvider>
      <ThemeProvider scheme="dark" theme={theme ?? undefined}>
        <Card borderLeft flex={1} height="fill" overflow="hidden" style={{colorScheme: 'dark'}}>
          {children}
        </Card>
      </ThemeProvider>
    </>
  )
}
