import {ThemeFonts} from '@sanity/ui'

export const fonts: ThemeFonts = {
  code: {
    family: '-apple-system-ui-monospace, "SF Mono", Menlo, Monaco, Consolas, monospace',
    weights: {
      regular: 500,
      medium: 600,
      semibold: 700,
      bold: 800,
    },
    sizes: [
      {
        ascenderHeight: 3,
        descenderHeight: 3,
        fontSize: 10,
        iconSize: 17,
        lineHeight: 13,
        letterSpacing: 0,
      },
      {
        ascenderHeight: 4,
        descenderHeight: 4,
        fontSize: 13,
        iconSize: 21,
        lineHeight: 17,
        letterSpacing: 0,
      },
      {
        ascenderHeight: 5,
        descenderHeight: 5,
        fontSize: 16,
        iconSize: 25,
        lineHeight: 21,
        letterSpacing: 0,
      },
      {
        ascenderHeight: 6,
        descenderHeight: 6,
        fontSize: 19,
        iconSize: 29,
        lineHeight: 25,
        letterSpacing: 0,
      },
      {
        ascenderHeight: 7,
        descenderHeight: 7,
        fontSize: 22,
        iconSize: 33,
        lineHeight: 29,
        letterSpacing: 0,
      },
    ],
  },
  heading: {
    family:
      'Larsseit, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
    weights: {
      regular: 700,
      medium: 800,
      semibold: 900,
      bold: 900,
    },
    sizes: [
      {
        ascenderHeight: 3,
        descenderHeight: 3,
        fontSize: 16,
        iconSize: 17,
        lineHeight: 25,
        letterSpacing: 0,
      },
      {
        ascenderHeight: 5,
        descenderHeight: 5,
        fontSize: 24,
        iconSize: 33,
        lineHeight: 33,
        letterSpacing: 0,
      },
      {
        ascenderHeight: 6,
        descenderHeight: 6,
        fontSize: 33,
        iconSize: 41,
        lineHeight: 41,
        letterSpacing: 0,
      },
      {
        ascenderHeight: 7,
        descenderHeight: 7,
        fontSize: 42,
        iconSize: 49,
        lineHeight: 49,
        letterSpacing: 0,
      },
      {
        ascenderHeight: 11,
        descenderHeight: 11,
        fontSize: 49,
        iconSize: 57,
        lineHeight: 57,
        letterSpacing: 0,
      },
      {
        ascenderHeight: 15,
        descenderHeight: 15,
        fontSize: 59,
        iconSize: 65,
        lineHeight: 57,
        letterSpacing: 0,
      },
    ],
  },
  label: {
    family:
      'Roboto Mono, Inter var, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
    weights: {
      regular: 600,
      medium: 700,
      semibold: 800,
      bold: 900,
    },
    sizes: [
      {
        ascenderHeight: 2,
        descenderHeight: 2,
        fontSize: 10,
        iconSize: 17,
        lineHeight: 11,
        letterSpacing: 0.5,
      },
      {
        ascenderHeight: 2,
        descenderHeight: 2,
        fontSize: 11,
        iconSize: 19,
        lineHeight: 12,
        letterSpacing: 0.5,
      },
      {
        ascenderHeight: 3,
        descenderHeight: 3,
        fontSize: 13,
        iconSize: 21,
        lineHeight: 15,
        letterSpacing: 0.5,
      },
      {
        ascenderHeight: 4,
        descenderHeight: 3,
        fontSize: 14,
        iconSize: 23,
        lineHeight: 17,
        letterSpacing: 0.5,
      },
      {
        ascenderHeight: 2,
        descenderHeight: 2,
        fontSize: 8.5,
        iconSize: 15,
        lineHeight: 10,
        letterSpacing: 0.5,
      },
    ],
  },
  text: {
    family:
      'Inter var, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
    weights: {
      regular: 500,
      medium: 600,
      semibold: 700,
      bold: 800,
    },
    sizes: [
      {
        ascenderHeight: 5,
        descenderHeight: 5,
        fontSize: 10,
        iconSize: 17,
        lineHeight: 17,
        letterSpacing: 0,
      },
      {
        ascenderHeight: 6,
        descenderHeight: 6,
        fontSize: 12,
        iconSize: 21,
        lineHeight: 21,
        letterSpacing: 0,
      },
      {
        ascenderHeight: 7,
        descenderHeight: 7,
        fontSize: 16,
        iconSize: 25,
        lineHeight: 25,
        letterSpacing: 0,
      },
      {
        ascenderHeight: 8,
        descenderHeight: 8,
        fontSize: 18,
        iconSize: 29,
        lineHeight: 29,
        letterSpacing: 0,
      },
      {
        ascenderHeight: 9,
        descenderHeight: 9,
        fontSize: 21,
        iconSize: 33,
        lineHeight: 33,
        letterSpacing: 0,
      },
    ],
  },
}
