/**
 * Captured from the hosted Themer service (themer.sanity.build) on
 * 2026-07-24, by evaluating the JavaScript module served for each URL and
 * serializing its exports. `colorSha256` is the SHA-256 hash of the
 * key-sorted JSON of the served theme's `color` object, and `samples` spot
 * checks a representative set of the served color values.
 */

export const hostedDefault = {
  url: 'https://themer.sanity.build/api/hues',
  colorSha256: '9ee427d349ce00014ae254cbdaa856eed1256c43dccd5163d81723bfb7cfc952',
  hues: {
    default: {
      lightest: '#fff',
      darkest: '#101112',
      mid: '#8690a0',
      midPoint: 500,
    },
    primary: {
      lightest: '#fff',
      darkest: '#101112',
      mid: '#2276fc',
      midPoint: 500,
    },
    transparent: {
      lightest: '#fff',
      darkest: '#101112',
      mid: '#8690a0',
      midPoint: 500,
    },
    positive: {
      lightest: '#fff',
      darkest: '#101112',
      mid: '#43d675',
      midPoint: 400,
    },
    caution: {
      lightest: '#fff',
      darkest: '#101112',
      mid: '#fbd024',
      midPoint: 300,
    },
    critical: {
      lightest: '#fff',
      darkest: '#101112',
      mid: '#f03e2f',
      midPoint: 500,
    },
  },
  samples: {
    'light.default.base.bg': '#fff',
    'light.default.base.fg': '#101112',
    'light.default.base.border': '#ced2d9',
    'light.default.base.focusRing': '#2276fc',
    'dark.default.base.bg': '#101112',
    'dark.default.base.fg': '#fff',
    'light.transparent.base.bg': '#f2f3f5',
    'dark.transparent.base.bg': '#1b1d20',
    'light.default.solid.primary.enabled.bg': '#2276fc',
    'dark.default.solid.primary.enabled.bg': '#5998fc',
    'light.default.solid.critical.hovered.bg': '#c33529',
    'light.default.muted.positive.enabled.fg': '#297343',
    'dark.default.muted.caution.pressed.bg': '#3e3a25',
    'light.default.button.ghost.default.enabled.border': '#ced2d9',
    'light.default.card.enabled.bg': '#fff',
    'dark.default.card.selected.bg': '#5998fc',
    'light.default.input.default.enabled.border': '#ced2d9',
    'light.default.input.default.hovered.border': '#b6bcc6',
    'dark.default.input.invalid.enabled.bg': '#342525',
    'light.default.selectable.primary.selected.bg': '#2276fc',
    'light.default.spot.gray': '#8690a0',
    'dark.default.spot.blue': '#5998fc',
    'light.default.syntax.keyword': '#ba3082',
    'dark.default.syntax.comment': '#777f8c',
    'light.primary.base.bg': '#e8f1fe',
    'dark.critical.base.border': '#69231d',
    'light.caution.solid.default.enabled.bg': '#b6941a',
    'dark.positive.muted.default.enabled.fg': '#7de4a2',
  },
} as const

export const hostedVerdant = {
  url: 'https://themer.sanity.build/api/hues?preset=verdant',
  colorSha256: '3e70ab34b3370683fa73171431e6209f10bb9c5a02eb17fb67a1e2ea3b70ed5b',
  hues: {
    default: {
      lightest: '#fcfdfd',
      darkest: '#0d1415',
      mid: '#5c9199',
      midPoint: 500,
    },
    primary: {
      lightest: '#fcfdfd',
      darkest: '#0d1415',
      mid: '#1cb485',
      midPoint: 400,
    },
    transparent: {
      lightest: '#fcfdfd',
      darkest: '#0d1415',
      mid: '#5c9199',
      midPoint: 500,
    },
    positive: {
      lightest: '#fcfdfd',
      darkest: '#0d1415',
      mid: '#43d675',
      midPoint: 300,
    },
    caution: {
      lightest: '#fcfdfd',
      darkest: '#0d1415',
      mid: '#fbd024',
      midPoint: 200,
    },
    critical: {
      lightest: '#fcfdfd',
      darkest: '#0d1415',
      mid: '#f03e2f',
      midPoint: 500,
    },
  },
  samples: {
    'light.default.base.bg': '#fcfdfd',
    'light.default.base.fg': '#0d1415',
    'light.default.base.border': '#bcd1d5',
    'light.default.base.focusRing': '#199972',
    'dark.default.base.bg': '#0d1415',
    'dark.default.base.fg': '#fcfdfd',
    'light.transparent.base.bg': '#ecf2f3',
    'dark.transparent.base.bg': '#142022',
    'light.default.solid.primary.enabled.bg': '#199871',
    'dark.default.solid.primary.enabled.bg': '#28ba8f',
    'light.default.solid.critical.hovered.bg': '#c03529',
    'light.default.muted.positive.enabled.fg': '#24663e',
    'dark.default.muted.caution.pressed.bg': '#353c29',
    'light.default.button.ghost.default.enabled.border': '#bcd1d5',
    'light.default.card.enabled.bg': '#fcfdfd',
    'dark.default.card.selected.bg': '#28ba8f',
    'light.default.input.default.enabled.border': '#bcd1d5',
    'light.default.input.default.hovered.border': '#b4bbc4',
    'dark.default.input.invalid.enabled.bg': '#2e2a2a',
    'light.default.selectable.primary.selected.bg': '#199871',
    'light.default.spot.gray': '#848f9f',
    'dark.default.spot.blue': '#579afc',
    'light.default.syntax.keyword': '#b83081',
    'dark.default.syntax.comment': '#75818d',
    'light.primary.base.bg': '#e0f3ee',
    'dark.critical.base.border': '#67241f',
    'light.caution.solid.default.enabled.bg': '#9e8117',
    'dark.positive.muted.default.enabled.fg': '#4fdb84',
  },
} as const

export const hostedCustom = {
  url: 'https://themer.sanity.build/api/hues?preset=pink-synth&primary=b595f9;400',
  colorSha256: '2029195cfcee1afed3f4f932312638fbf4995b00ec33739a91b1cb15b857524f',
  hues: {
    default: {
      lightest: '#f7f2f5',
      darkest: '#171721',
      mid: '#8b6584',
      midPoint: 500,
    },
    primary: {
      lightest: '#f7f2f5',
      darkest: '#171721',
      mid: '#b595f9',
      midPoint: 400,
    },
    transparent: {
      lightest: '#f7f2f5',
      darkest: '#171721',
      mid: '#503a4c',
      midPoint: 500,
    },
    positive: {
      lightest: '#f7f2f5',
      darkest: '#171721',
      mid: '#10b981',
      midPoint: 500,
    },
    caution: {
      lightest: '#f7f2f5',
      darkest: '#171721',
      mid: '#fde047',
      midPoint: 300,
    },
    critical: {
      lightest: '#f7f2f5',
      darkest: '#171721',
      mid: '#fe3459',
      midPoint: 500,
    },
  },
  samples: {
    'light.default.base.bg': '#f7f2f5',
    'light.default.base.fg': '#171721',
    'light.default.base.border': '#b4a8b1',
    'light.default.base.focusRing': '#9a80d5',
    'dark.default.base.bg': '#171721',
    'dark.default.base.fg': '#f7f2f5',
    'light.transparent.base.bg': '#ece3e9',
    'dark.transparent.base.bg': '#221e2a',
    'light.default.solid.primary.enabled.bg': '#9579cd',
    'dark.default.solid.primary.enabled.bg': '#bc9ffa',
    'light.default.solid.critical.hovered.bg': '#c92c4a',
    'light.default.muted.positive.enabled.fg': '#117256',
    'dark.default.muted.caution.pressed.bg': '#494542',
    'light.default.button.ghost.default.enabled.border': '#b4a8b1',
    'light.default.card.enabled.bg': '#f7f2f5',
    'dark.default.card.selected.bg': '#bc9ffa',
    'light.default.input.default.enabled.border': '#b4a8b1',
    'light.default.input.default.hovered.border': '#b0b2be',
    'dark.default.input.invalid.enabled.bg': '#412e42',
    'light.default.selectable.primary.selected.bg': '#9579cd',
    'light.default.spot.gray': '#82899a',
    'dark.default.spot.blue': '#5e9bfc',
    'light.default.syntax.keyword': '#b42e7d',
    'dark.default.syntax.comment': '#7b8293',
    'light.primary.base.bg': '#eee6f5',
    'dark.critical.base.border': '#732237',
    'light.caution.solid.default.enabled.bg': '#b69c33',
    'dark.positive.muted.default.enabled.fg': '#79d6bc',
  },
} as const
