// re-export for backwards compatibility
export {
  COLOR_CONFIG_BASE_KEYS,
  COLOR_CONFIG_BASE_TONES,
  COLOR_CONFIG_BLEND_KEYS,
  COLOR_CONFIG_STATE_KEYS,
  COLOR_CONFIG_STATE_TONES,
  THEME_COLOR_BASE_TONES,
  THEME_COLOR_BLEND_MODES,
  THEME_COLOR_BUTTON_MODES,
  THEME_COLOR_STATES,
  THEME_COLOR_STATE_TONES,
  buildTheme,
  createColorTheme,
  hexToRgb,
  hslToRgb,
  isColorBlendModeValue,
  isColorButtonMode,
  isColorConfigBaseKey,
  isColorConfigBaseTone,
  isColorConfigBlendKey,
  isColorConfigStateKey,
  isColorConfigStateTone,
  isColorHueKey,
  isColorOpacityValue,
  isColorTintKey,
  isColorTokenValue,
  isColorValue,
  multiply,
  parseColor,
  parseTokenKey,
  parseTokenValue,
  rgbToHex,
  rgbToHsl,
  rgba,
  rgbaToRGBA,
  screen,
  studioTheme,
  type BaseTheme,
  type BoxShadow,
  type CSSObject,
  type ColorBlendModeTokenValue,
  type ColorConfigBaseKey,
  type ColorConfigBaseTone,
  type ColorConfigBlendKey,
  type ColorConfigOpacityValue,
  type ColorConfigStateKey,
  type ColorConfigStateTone,
  type ColorConfigValue,
  type HSL,
  type PartialThemeColorBuilderOpts,
  type RGB,
  type RGBA,
  type RootTheme,
  type Theme,
  type ThemeAvatar,
  type ThemeColor,
  type ThemeColorBase,
  type ThemeColorBaseTokens,
  type ThemeColorBaseToneKey,
  type ThemeColorBlendModeKey,
  type ThemeColorBuilderOpts,
  type ThemeColorButton,
  type ThemeColorButtonModeKey,
  type ThemeColorButtonState,
  type ThemeColorButtonStates,
  type ThemeColorButtonTokens,
  type ThemeColorButtonTones,
  type ThemeColorCard,
  type ThemeColorCardState,
  type ThemeColorGenericState,
  type ThemeColorInput,
  type ThemeColorInputState,
  type ThemeColorInputStates,
  type ThemeColorMuted,
  type ThemeColorMutedTone,
  type ThemeColorName,
  type ThemeColorScheme,
  type ThemeColorSchemeKey,
  type ThemeColorSchemes,
  type ThemeColorSelectable,
  type ThemeColorSelectableState,
  type ThemeColorSelectableStates,
  type ThemeColorSolid,
  type ThemeColorSolidTone,
  type ThemeColorSpot,
  type ThemeColorSpotKey,
  type ThemeColorStateKey,
  type ThemeColorStateTokens,
  type ThemeColorStateToneKey,
  type ThemeColorStatesTokens,
  type ThemeColorSyntax,
  type ThemeColorTokenValue,
  type ThemeColorTokens,
  type ThemeColorToneKey,
  type ThemeConfig,
  type ThemeFocusRing,
  type ThemeFont,
  type ThemeFontKey,
  type ThemeFontSize,
  type ThemeFontWeight,
  type ThemeFontWeightKey,
  type ThemeFonts,
  type ThemeInput,
  type ThemeLayer,
  type ThemeShadow,
  type ThemeStyles,
  type TokenBaseKeyNode,
  type TokenBlendModeValueNode,
  type TokenButtonKeyNode,
  type TokenColorValueNode,
  type TokenHueValueNode,
  type TokenKeyNode,
  type TokenValueNode,
} from '@sanity/ui/theme'
