export const atomRoutes = [
  {slug: 'avatar', title: 'Avatar'},
  {slug: 'badge', title: 'Badge'},
  {slug: 'box', title: 'Box'},
  {slug: 'button', title: 'Button'},
  {slug: 'card', title: 'Card'},
  {slug: 'checkbox', title: 'Checkbox'},
  {slug: 'code', title: 'Code'},
  {slug: 'container', title: 'Container'},
  {slug: 'flex', title: 'Flex'},
  {slug: 'heading', title: 'Heading'},
  {slug: 'icon', title: 'Icon'},
  {slug: 'inline', title: 'Inline'},
  {slug: 'kbd', title: 'KBD'},
  {slug: 'popover', title: 'Popover'},
  {slug: 'radio', title: 'Radio'},
  {slug: 'stack', title: 'Stack'},
  {slug: 'switch', title: 'Switch'},
  {slug: 'text-area', title: 'TextArea'},
  {slug: 'text-input', title: 'TextInput'},
  {slug: 'text', title: 'Text'},
  {slug: 'tooltip', title: 'Tooltip'},
]
