import {RootTheme} from '@sanity/ui/theme'

/**
 * The tint (between 50 and 950) that a `Hue`'s `mid` color is placed at.
 *
 * @public
 */
export type HueMidPoint = 50 | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900 | 950

/**
 * A single hue configuration, matching the hosted Themer service
 * (themer.sanity.build) hue format.
 *
 * @public
 */
export interface Hue {
  /** The mid color of the hue's tint ramp, as a hex color */
  mid: string
  /** The tint that `mid` is placed at — the rest of the ramp is interpolated */
  midPoint: HueMidPoint
  /** The hex color that the ramp's lightest end interpolates towards */
  lightest: string
  /** The hex color that the ramp's darkest end interpolates towards */
  darkest: string
}

/**
 * The six hues a legacy Themer theme is generated from.
 *
 * @public
 */
export interface Hues {
  default: Hue
  transparent: Hue
  primary: Hue
  positive: Hue
  caution: Hue
  critical: Hue
}

/**
 * `Hues` where every hue, and every property of each hue, is optional.
 * Omitted properties fall back to the default Studio theme hues.
 *
 * @public
 */
export type PartialHues = {[TKey in keyof Hues]?: Partial<Hues[TKey]>}

/**
 * A theme generated by `createTheme`, compatible with the `theme` property in
 * a Sanity Studio `defineConfig`.
 *
 * @public
 */
export type LegacyTheme = RootTheme & {
  /**
   * Marks the theme as generated by Themer, which Sanity Studio detects to
   * reconcile fonts and other non-color attributes.
   */
  __themer: true
  /**
   * Set to `undefined` so that `@sanity/ui` derives the v2 theme internally
   * from the generated colors.
   */
  v2: undefined
}

/**
 * A preset theme, carried over from the hosted Themer service.
 *
 * @public
 */
export interface ThemePreset {
  slug: string
  title: string
  /**
   * The canonical search params for this preset — the same query that
   * `https://themer.sanity.build/api/hues` served the preset for.
   */
  searchParams: string
  /** The preset's resolved hues, ready to pass to `createTheme` */
  hues: Hues
}
