import {ColorTints, hues} from '@sanity/color'
import {ThemeColorName} from '../types'
import {createCssVars} from './createCssVars'

export const tones: Record<ThemeColorName, ColorTints> = {
  default: hues.gray,
  transparent: hues.gray,
  primary: hues.gray,
  positive: hues.cyan,
  caution: hues.yellow,
  critical: hues.red,
} as const

describe('css variables', () => {
  it('Should create the variables when no default tone is provided', () => {
    const result = createCssVars('light', tones)
    const expected = {
      '--default-text-primary': '#25282d',
      '--default-text-secondary': '#5e6673',
      '--default-text-inactive': '#767f8f',
      '--default-text-code': '#5e6673',
      '--default-text-muted': '#5e6673',
      '--default-text-link': '#166bfe',
      '--default-text-accent': '#e22e1d',
      '--default-bg-base': '#ffffff',
      '--default-bg-base-hover': '#f3f4f7',
      '--default-bg-base-active': '#e4e7ec',
      '--default-bg-accent': '#25282d',
      '--default-bg-accent-hover': '#1c1e22',
      '--default-bg-accent-active': '#111213',
      '--default-bg-tint': '#f3f4f7',
      '--default-bg-tint-code': '#f3f4f7',
      '--default-icon-default': '#767f8f',
      '--default-icon-inverted': '#ffffff',
      '--default-border-base': '#e4e7ec',
      '--default-border-base-hover': '#c4cad4',
      '--default-border-accent': '#5e6673',
      '--default-border-accent-inverted': '#ffffff',
      '--default-base-bg-card': '#ffffff',
      '--default-base-bg-raw': '#ffffff',
      '--default-base-shadow-outline-color': 'rgba(118,127,143,0.4)',
      '--default-base-shadow-umbra-color': 'rgba(118,127,143,0.2)',
      '--default-base-shadow-penumbra-color': 'rgba(118,127,143,0.14)',
      '--default-base-shadow-ambient-color': 'rgba(118,127,143,0.12)',
      '--default-base-text-color': '#ffffff',
      '--default-skeleton-from': '#e4e7ec',
      '--default-skeleton-to': 'rgba(243,244,247,0.5)',
      '--transparent-text-primary': '#25282d',
      '--transparent-text-secondary': '#5e6673',
      '--transparent-text-inactive': '#767f8f',
      '--transparent-text-code': '#5e6673',
      '--transparent-text-muted': '#5e6673',
      '--transparent-text-link': '#166bfe',
      '--transparent-text-accent': '#e22e1d',
      '--transparent-bg-base': '#ffffff',
      '--transparent-bg-base-hover': '#f3f4f7',
      '--transparent-bg-base-active': '#e4e7ec',
      '--transparent-bg-accent': '#767f8f',
      '--transparent-bg-accent-hover': '#5e6673',
      '--transparent-bg-accent-active': '#49505a',
      '--transparent-bg-tint': '#f3f4f7',
      '--transparent-bg-tint-code': '#f3f4f7',
      '--transparent-icon-default': '#767f8f',
      '--transparent-icon-inverted': '#ffffff',
      '--transparent-border-base': '#e4e7ec',
      '--transparent-border-base-hover': '#c4cad4',
      '--transparent-border-accent': '#767f8f',
      '--transparent-border-accent-inverted': '#ffffff',
      '--transparent-base-bg-card': '#f3f4f7',
      '--transparent-base-bg-raw': '#ffffff',
      '--transparent-base-shadow-outline-color': 'rgba(118,127,143,0.4)',
      '--transparent-base-shadow-umbra-color': 'rgba(118,127,143,0.2)',
      '--transparent-base-shadow-penumbra-color': 'rgba(118,127,143,0.14)',
      '--transparent-base-shadow-ambient-color': 'rgba(118,127,143,0.12)',
      '--transparent-base-text-color': '#ffffff',
      '--transparent-skeleton-from': '#e4e7ec',
      '--transparent-skeleton-to': 'rgba(243,244,247,0.5)',
      '--primary-text-primary': '#25282d',
      '--primary-text-secondary': '#5e6673',
      '--primary-text-inactive': '#767f8f',
      '--primary-text-code': '#5e6673',
      '--primary-text-muted': '#5e6673',
      '--primary-text-link': '#166bfe',
      '--primary-text-accent': '#e22e1d',
      '--primary-bg-base': '#ffffff',
      '--primary-bg-base-hover': '#f3f4f7',
      '--primary-bg-base-active': '#e4e7ec',
      '--primary-bg-accent': '#25282d',
      '--primary-bg-accent-hover': '#1c1e22',
      '--primary-bg-accent-active': '#111213',
      '--primary-bg-tint': '#f3f4f7',
      '--primary-bg-tint-code': '#f3f4f7',
      '--primary-icon-default': '#767f8f',
      '--primary-icon-inverted': '#ffffff',
      '--primary-border-base': '#e4e7ec',
      '--primary-border-base-hover': '#c4cad4',
      '--primary-border-accent': '#5e6673',
      '--primary-border-accent-inverted': '#ffffff',
      '--primary-base-bg-card': '#f3f4f7',
      '--primary-base-bg-raw': '#ffffff',
      '--primary-base-shadow-outline-color': 'rgba(118,127,143,0.4)',
      '--primary-base-shadow-umbra-color': 'rgba(118,127,143,0.2)',
      '--primary-base-shadow-penumbra-color': 'rgba(118,127,143,0.14)',
      '--primary-base-shadow-ambient-color': 'rgba(118,127,143,0.12)',
      '--primary-base-text-color': '#ffffff',
      '--primary-skeleton-from': '#e4e7ec',
      '--primary-skeleton-to': 'rgba(243,244,247,0.5)',
      '--positive-text-primary': '#0f2f2a',
      '--positive-text-secondary': '#099079',
      '--positive-text-inactive': '#15ac93',
      '--positive-text-code': '#099079',
      '--positive-text-muted': '#099079',
      '--positive-text-link': '#166bfe',
      '--positive-text-accent': '#e22e1d',
      '--positive-bg-base': '#ffffff',
      '--positive-bg-base-hover': '#f3f4f7',
      '--positive-bg-base-active': '#dcfef8',
      '--positive-bg-accent': '#1ed2b4',
      '--positive-bg-accent-hover': '#15ac93',
      '--positive-bg-accent-active': '#099079',
      '--positive-bg-tint': '#dcfef8',
      '--positive-bg-tint-code': '#dcfef8',
      '--positive-icon-default': '#15ac93',
      '--positive-icon-inverted': '#ffffff',
      '--positive-border-base': '#bafcf1',
      '--positive-border-base-hover': '#72f8e1',
      '--positive-border-accent': '#1ed2b4',
      '--positive-border-accent-inverted': '#ffffff',
      '--positive-base-bg-card': '#dcfef8',
      '--positive-base-bg-raw': '#ffffff',
      '--positive-base-shadow-outline-color': 'rgba(21,172,147,0.4)',
      '--positive-base-shadow-umbra-color': 'rgba(21,172,147,0.2)',
      '--positive-base-shadow-penumbra-color': 'rgba(21,172,147,0.14)',
      '--positive-base-shadow-ambient-color': 'rgba(21,172,147,0.12)',
      '--positive-base-text-color': '#ffffff',
      '--positive-skeleton-from': '#bafcf1',
      '--positive-skeleton-to': 'rgba(220,254,248,0.5)',
      '--caution-text-primary': '#332514',
      '--caution-text-secondary': '#9f760f',
      '--caution-text-inactive': '#c69910',
      '--caution-text-code': '#9f760f',
      '--caution-text-muted': '#9f760f',
      '--caution-text-link': '#166bfe',
      '--caution-text-accent': '#e22e1d',
      '--caution-bg-base': '#ffffff',
      '--caution-bg-base-hover': '#fefbe7',
      '--caution-bg-base-active': '#faf3b2',
      '--caution-bg-accent': '#c69910',
      '--caution-bg-accent-hover': '#9f760f',
      '--caution-bg-accent-active': '#785612',
      '--caution-bg-tint': '#fefbe7',
      '--caution-bg-tint-code': '#fefbe7',
      '--caution-icon-default': '#c69910',
      '--caution-icon-inverted': '#ffffff',
      '--caution-border-base': '#faf3b2',
      '--caution-border-base-hover': '#f5e18a',
      '--caution-border-accent': '#c69910',
      '--caution-border-accent-inverted': '#ffffff',
      '--caution-base-bg-card': '#fefbe7',
      '--caution-base-bg-raw': '#ffffff',
      '--caution-base-shadow-outline-color': 'rgba(198,153,16,0.4)',
      '--caution-base-shadow-umbra-color': 'rgba(198,153,16,0.2)',
      '--caution-base-shadow-penumbra-color': 'rgba(198,153,16,0.14)',
      '--caution-base-shadow-ambient-color': 'rgba(198,153,16,0.12)',
      '--caution-base-text-color': '#ffffff',
      '--caution-skeleton-from': '#faf3b2',
      '--caution-skeleton-to': 'rgba(254,251,231,0.5)',
      '--critical-text-primary': '#3d1815',
      '--critical-text-secondary': '#b5291c',
      '--critical-text-inactive': '#f38177',
      '--critical-text-code': '#b5291c',
      '--critical-text-muted': '#b5291c',
      '--critical-text-link': '#166bfe',
      '--critical-text-accent': '#e22e1d',
      '--critical-bg-base': '#ffffff',
      '--critical-bg-base-hover': '#fde9e8',
      '--critical-bg-base-active': '#fcd7d4',
      '--critical-bg-accent': '#e22e1d',
      '--critical-bg-accent-hover': '#b5291c',
      '--critical-bg-accent-active': '#8e241a',
      '--critical-bg-tint': '#fde9e8',
      '--critical-bg-tint-code': '#fde9e8',
      '--critical-icon-default': '#e22e1d',
      '--critical-icon-inverted': '#ffffff',
      '--critical-border-base': '#fcd7d4',
      '--critical-border-base-hover': '#f8b1aa',
      '--critical-border-accent': '#e22e1d',
      '--critical-border-accent-inverted': '#ffffff',
      '--critical-base-bg-card': '#fde9e8',
      '--critical-base-bg-raw': '#ffffff',
      '--critical-base-shadow-outline-color': 'rgba(226,46,29,0.4)',
      '--critical-base-shadow-umbra-color': 'rgba(226,46,29,0.2)',
      '--critical-base-shadow-penumbra-color': 'rgba(226,46,29,0.14)',
      '--critical-base-shadow-ambient-color': 'rgba(226,46,29,0.12)',
      '--critical-base-text-color': '#ffffff',
      '--critical-skeleton-from': '#fcd7d4',
      '--critical-skeleton-to': 'rgba(253,233,232,0.5)',
      '--card-accent-fg-color': 'var(--default-text-accent)',
      '--card-bg-color': 'var(--default-bg-base)',
      '--card-bg-image': 'inherit',
      '--card-bg2-color': 'var(--default-bg-tint)',
      '--card-code-bg-color': 'var(--default-bg-tint-code)',
      '--card-code-fg-color': 'var(--default-text-code)',
      '--card-fg-color': 'var(--default-text-primary)',
      '--card-focus-ring-color': 'var(--positive-bg-accent)',
      '--card-hairline-hard-color': 'var(--default-border-base)',
      '--card-hairline-soft-color': 'var(--default-border-base)',
      '--card-icon-color': 'var(--default-icon-default)',
      '--card-link-color': 'var(--default-text-link)',
      '--card-link-fg-color': 'var(--default-text-link)',
      '--card-muted-fg-color': 'var(--default-text-secondary)',
      '--card-shadow-ambient-color': 'var(--default-base-shadow-ambient-color)',
      '--card-shadow-outline-color': 'var(--default-base-shadow-outline-color)',
      '--card-shadow-penumbra-color': 'var(--default-base-shadow-penumbra-color)',
      '--card-shadow-umbra-color': 'var(--default-base-shadow-umbra-color)',
      '--card-skeleton-color-from': 'var(--default-skeleton-from)',
      '--card-skeleton-color-to': 'var(--default-skeleton-to)',
    }

    expect(result).toEqual(expected)
  })
  it('Should create the variables when a default tone is provided in light mode', () => {
    const defaultVariables = createCssVars('light', tones)
    const result = createCssVars('light', tones, 'caution')

    expect(result['--default-text-primary']).toEqual(result['--caution-text-primary'])
    // It's not equal because it has been mixed with the default bg
    expect(result['--default-text-primary']).not.toEqual(defaultVariables['--caution-text-primary'])

    expect(result['--default-text-secondary']).toEqual(result['--caution-text-secondary'])
    // It's not equal because it has been mixed with the default bg
    expect(result['--default-text-secondary']).not.toEqual(
      defaultVariables['--caution-text-secondary'],
    )
    // The default base bg should not be mixed
    expect(result['--default-bg_base']).toEqual(defaultVariables['--caution-card_base_bg'])

    expect(result['--default-base-shadow-ambient-color']).toEqual(
      defaultVariables['--caution-base-shadow-ambient-color'],
    )
    expect(result['--default-base-shadow-ambient-color']).not.toEqual(
      defaultVariables['--positive-base-shadow-ambient-color'],
    )
  })
  it('Should create the variables when a default tone is provided in dark mode', () => {
    const defaultVariables = createCssVars('dark', tones)
    const result = createCssVars('dark', tones, 'caution')

    expect(result['--default-text-primary']).toEqual(result['--caution-text-primary'])
    // It's not equal because it has been mixed with the default bg
    expect(result['--default-text-primary']).not.toEqual(defaultVariables['--caution-text-primary'])

    expect(result['--default-text-secondary']).toEqual(result['--caution-text-secondary'])
    // It's not equal because it has been mixed with the default bg
    expect(result['--default-text-secondary']).not.toEqual(
      defaultVariables['--caution-text-secondary'],
    )
    // The base bg should not be mixed
    expect(result['--default-bg_base']).toEqual(defaultVariables['--caution-card_base_bg'])
  })
})
