name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  chromatic:
    name: Run oxlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Run oxlint
        run: pnpm lint --format github
