name: CI & Release

on:
  pull_request:
  push:
    branches:
      - v2
      - main
      - v4

permissions:
  contents: read # for checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - run: pnpm install
      - run: pnpm ts:check
      - run: pnpm build

  lint:
    needs: [build]
    name: "ESLint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - run: pnpm install
      - run: pnpm lint -f gha --max-warnings 0

  test:
    needs: [build]
    runs-on: ${{ matrix.platform }}
    name: Node.js ${{ matrix.node-version }} / ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        # node-version: [lts/*, current]
        node-version: [lts/*]
        include:
          - platform: macos-latest
            node-version: lts/*
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm install
      - run: pnpm test

  storybook-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - run: pnpm install
      - name: Store Playwright's version
        id: playwright-version
        run: |
          PLAYWRIGHT_VERSION=$(pnpm --filter sanity-ui-storybook exec playwright --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
          echo "Playwright's version: $PLAYWRIGHT_VERSION"
          echo "version=${PLAYWRIGHT_VERSION}" >> "$GITHUB_OUTPUT"
      - name: Cache Playwright browsers for Playwright's version
        id: cache-playwright-browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ steps.playwright-version.outputs.version }}-playwright-browsers-chromium
      - name: Install Playwright browsers
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: pnpm --filter sanity-ui-storybook exec playwright install --with-deps chromium
      - run: pnpm test:browser
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: vitest-failure-screenshots
          path: apps/storybook/**/__screenshots__/
          if-no-files-found: ignore

  release:
    permissions:
      id-token: write # to enable use of OIDC for npm provenance
    name: "Semantic release"
    needs: [lint, test, storybook-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.ECOSPARK_APP_ID }}
          private-key: ${{ secrets.ECOSPARK_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v5
        with:
          # Need to fetch entire commit history to
          # analyze every commit since last release
          fetch-depth: 0
          # Uses generated token to allow pushing commits back
          token: ${{ steps.app-token.outputs.token }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
      - uses: pnpm/action-setup@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - run: pnpm install
      # Branches that will release new versions are defined in packages/ui/package.json
      - run: pnpm --filter @sanity/ui exec semantic-release
        env:
          NPM_CONFIG_PROVENANCE: true
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
