/**
 * These are internal exports for usage in `@sanity/visual-editing` and `@sanity/insert-menu`,
 * which are used in environments where the regular `@sanity/ui` export is far too heavy due to imports from refractor and more.
 */
export {studioTheme} from '../src/ui/_compat'
export {ThemeProvider, type ThemeProviderProps} from '../src/ui/_compat/theme/themeProvider'
export {useTheme_v2} from '../src/ui/_compat/theme/useTheme'
export {Hotkeys, type HotkeysProps} from '../src/ui/components/hotkeys/hotkeys'
export {Menu, type MenuProps} from '../src/ui/components/menu/menu'
export {MenuDivider} from '../src/ui/components/menu/menuDivider'
export {MenuGroup, type MenuGroupProps} from '../src/ui/components/menu/menuGroup'
export {MenuItem, type MenuItemProps} from '../src/ui/components/menu/menuItem'
export {Tab, type TabProps} from '../src/ui/components/tab/tab'
export {TabList, type TabListProps} from '../src/ui/components/tab/tabList'
export {isHTMLAnchorElement, isHTMLElement} from '../src/ui/helpers/element'
export {usePrefersDark} from '../src/ui/hooks/usePrefersDark'
export {Box, type BoxProps} from '../src/ui/primitives/box/box'
export {Button, type ButtonProps} from '../src/ui/primitives/button/button'
export {Card, type CardProps} from '../src/ui/primitives/card/card'
export {Flex, type FlexProps} from '../src/ui/primitives/flex/flex'
export {Grid, type GridProps} from '../src/ui/primitives/grid/grid'
export {Popover, type PopoverProps} from '../src/ui/primitives/popover/popover'
export {Spinner, type SpinnerProps} from '../src/ui/primitives/spinner/spinner'
export {Stack, type StackProps} from '../src/ui/primitives/stack/stack'
export {Text, type TextProps} from '../src/ui/primitives/text/text'
export {TextInput, type TextInputProps} from '../src/ui/primitives/textInput/textInput'
export {Tooltip, type TooltipProps} from '../src/ui/primitives/tooltip/tooltip'
export type {PopoverMargins} from '../src/ui/types/popover'
export {LayerProvider} from '../src/ui/utils/layer/layerProvider'
export {Portal, type PortalProps} from '../src/ui/utils/portal/portal'
export {PortalProvider, type PortalProviderProps} from '../src/ui/utils/portal/portalProvider'
